# Generated by Django 4.0.5 on 2022-06-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_telegramuser_alter_order_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
